repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 22.3.0  # Replace with a known working version
    hooks:
      - id: black
        additional_dependencies: ['click==8.0.4']  # Specify a compatible click version
